[package]
name = "webdav-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
network-test = []
not-net-test = []

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
quick-xml = { version = "0.38", features = ["serialize"] }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "serde",
] }
mime = "0.3.17"
percent-encoding = "2.3.2"
base64 = { version = "0.22" }
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "json",
    "stream",
    "gzip",
    "cookies",
] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
    "fs",
] }
sha2 = { version = "0.10.9" }
url = "2.5.4"
thiserror = "2.0.16"

[dev-dependencies]
futures-util = "0.3"
wiremock = "0.6.5"

[[test]]
name = "auth"
path = "tests/auth/mod.rs"

[[test]]
name = "get"
path = "tests/get/mod.rs"

[[test]]
name = "propfind"
path = "tests/propfind/mod.rs"
